### ISSUE TITLE
Issue with outdated keyword file

### ISSUE THREAD

**Issue by thatbitchsystem** [DevMiser/DaVinci#1]
Terminal output when attempting to run the program after fresh install

pi@raspberrypi:~/DaVinci $ python3 DaVinci.py
[ERROR] keyword file belongs to a different version of the library. keyword file is `2.1.0` while the library is                                                                                                                 `2.2.0`.
[ERROR] loading keyword file at `/home/pi/.local/lib/python3.9/site-packages/pvporcupine/resources/keyword_files/                                                                                                                raspberry-pi/DaVinci_raspberry-pi.ppn` failed with `INVALID_ARGUMENT`
Traceback (most recent call last):
  File "/home/pi/DaVinci/DaVinci.py", line 288, in <module>
    wake_word()
  File "/home/pi/DaVinci/DaVinci.py", line 142, in wake_word
    porcupine = pvporcupine.create(keywords=["computer", "jarvis", "DaVinci",],
  File "/home/pi/.local/lib/python3.9/site-packages/pvporcupine/_factory.py", line 69, in create
    return Porcupine(
  File "/home/pi/.local/lib/python3.9/site-packages/pvporcupine/_porcupine.py", line 164, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine._porcupine.PorcupineInvalidArgumentError
^CException ignored in: <module 'threading' from '/usr/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1428, in _shutdown
    lock.acquire()
KeyboardInterrupt:

**Comment by thatbitchsystem** [comment]
Resolved issue with the following commands:
$ mv /home/pi/.local/lib/python3.9/site-packages/pvporcupine/resources/keyword_files/raspberry-pi/DaVinci_raspberry-pi.ppn /home/pi/DaVinci/
$ pip3 uninstall pvporcupine
$ pip3 install pvporcupine==2.1.0
$  mv /home/pi/DaVinci/DaVinci_raspberry-pi.ppn /home/pi/.local/lib/python3.9/site-packages/pvporcupine/resources/keyword_files/raspberry-pi
$ python3 DaVinci.py

**Comment by DevMiser** [comment]
The keyword file is now updated
