### ISSUE TITLE
Issue with wake word / keyword file

### ISSUE THREAD

**Issue by mrpundir** [DevMiser/DaVinci#15]
Terminal output is as follows(on fresh install):

sudo python3 DaVinci.py
Traceback (most recent call last):
  File "/home/rickkpr/DaVinci/DaVinci.py", line 295, in <module>
    wake_word()
  File "/home/rickkpr/DaVinci/DaVinci.py", line 146, in wake_word
    porcupine = pvporcupine.create(keywords=["computer", "jarvis", "DaVinci",],
  File "/usr/local/lib/python3.10/dist-packages/pvporcupine/__init__.py", line 67, in create
    raise ValueError(
ValueError: One or more keywords are not available by default. Available default keywords are:\npicovoice, computer, grasshopper, hey barista, terminator, ok google, hey siri, bumblebee, grapefruit, jarvis, hey google, pico clock, porcupine, alexa, americano, blueberry
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt:

I also tried using the below resolution, but it did not worked for me:

[thatbitchsystem](https://github.com/thatbitchsystem) commented [on Apr 16](https://github.com/DevMiser/DaVinci/issues/1#issuecomment-1509993307)
Resolved issue with the following commands:
$ mv /home/pi/.local/lib/python3.9/site-packages/pvporcupine/resources/keyword_files/raspberry-pi/DaVinci_raspberry-pi.ppn /home/pi/DaVinci/
$ pip3 uninstall pvporcupine
$ pip3 install pvporcupine==2.1.0
$ mv /home/pi/DaVinci/DaVinci_raspberry-pi.ppn /home/pi/.local/lib/python3.9/site-packages/pvporcupine/resources/keyword_files/raspberry-pi
$ python3 DaVinci.py

Please note, in the above step/resolution, the file is named 'DaVinci_raspberry-pi.ppn' [single underscore in file name] however, in the latest build available, the file is named 'DaVinci__raspberry-pi.ppn' with two consecutive underscore in the name of file. I tried the above resolution and/or also tried to rename the file to 'DaVinci_raspberry-pi.ppn', but still it does not work. Please point me to the right direction/should I downgrade my python version to 3.9

FYI - my python version is 3.10, so I made the changes to the path accordingly. Thanks.

**Comment by DevMiser** [comment]
You should also reinstall the current version of pvporcupine.

**Comment by mrpundir** [comment]
1 - Took care of this part: 'please note that there are two blank spaces in the above command - between "mv" and "/home" and between ".ppn" and "/home". Be sure to include them'
2 - Took care of this as well: 'You should also reinstall the current version of pvporcupine'

Still, getting same error. FYI - my OS is Ubuntu 22.04.3 LTS (Jammy Jellyfish) on Raspberry Pi 4 with python version 3.10
I have still not tried downgrading the python version down to 3.9.3 Please let me know if the issue is there with Ubuntu OS maybe(aarch64). Thanks again for your prompt reply earlier. Waiting up to hear more from you, will keep you updated as well.

**Comment by BerkSmash1984** [comment]
I am getting the same error regarding the wake word, as of 10/6 with a fresh install of DaVinci on a freshly flashed DietPi OS on my RPI4B:

![image](https://github.com/DevMiser/DaVinci/assets/104693081/c9885e63-b979-4e3d-bbe2-db1b72ab745f)

The latest version of DietPi OS (v8.22.3) has Python 3.11 installed. Any ideas?

**Comment by DevMiser** [comment]
I recommend trying the following:
Modify the DaVinci.py file by deleting the word "Davinci" from line 146 so that it now reads "porcupine = pvporcupine.create(keywords=["computer", "jarvis",],"
Also delete one of the "0.1"s from line 148 so that it now reads:  "sensitivities=[0.1, 0.1],"
And then try waking it up by saying either "computer" or "jarvis"
If you continue to get an error that includes "One or more keywords are not available by default...", then there is likely  an issue with where the keyword file is located in your directories that you will need to track down
If there is an error that does not include that phrase, it could be a host of things including that there may be dependencies not included in DietPi OS.  I would then recommend using the official Raspberry Pi 64-bit OS.  https://www.raspberrypi.com/software/ Make certain to use the 64-bit version.  DaVinci will word correctly if you do so and follow the instructions exactly.
Good luck and I hope you get it working.

**Comment by mrpundir** [comment]
@BerkSmash1984 Thanks for chiming in, and please do let me know if the above reply from @DevMiser was able to resolve the issue. I am on a trip outside and may not be able to check right away on my Raspberry Pi setup(with Ubuntu OS 64 bit). Much thanks to both of you :)

**Comment by BerkSmash1984** [comment]
I definitely will. I'm currently out of town but will give it a go when I return. I wish I had just stuck to Bullseye OS but DietPi sounded fun. I'll give the recommendation a go and then likely reflash to Bullseye. Unfortunately I will also have to redo my PiHole and MagicMirror, as everything is running on this Pi 🙃

**Comment by mrpundir** [comment]
Finally, it seems like the issue is with OS compatibility only.

This project will work with Raspberry Pi OS(Bullseye) only, and is not compatible with other 64bit OS like Ubuntu 22.04.3 LTS OS, or DietPi OS, etc. due to missing dependencies maybe(OS specific).

May try in future with Bullseye OS. Closing the raised issue now.

Thanks all :)
