### ISSUE TITLE
Tried it on my new Raspberry Pi 5, processor not supported

### ISSUE THREAD

**Issue by tmart42** [DevMiser/DaVinci#26]
Finished the install on a new Pi 5, and am getting the following traceback:

Traceback (most recent call last):
  File "/home/ty/DaVinci/DaVinci.py", line 8, in <module>
    import pvcobra
  File "/home/ty/.local/lib/python3.11/site-packages/pvcobra/__init__.py", line 12, in <module>
    from ._factory import *
  File "/home/ty/.local/lib/python3.11/site-packages/pvcobra/_factory.py", line 15, in <module>
    from ._util import *
  File "/home/ty/.local/lib/python3.11/site-packages/pvcobra/_util.py", line 64, in <module>
    _PV_SYSTEM, _PV_MACHINE = _pv_platform()
                              ^^^^^^^^^^^^^^
  File "/home/ty/.local/lib/python3.11/site-packages/pvcobra/_util.py", line 57, in _pv_platform
    pv_machine = _pv_linux_machine(platform.machine())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ty/.local/lib/python3.11/site-packages/pvcobra/_util.py", line 48, in _pv_linux_machine
    raise NotImplementedError('Unsupported CPU.\n%s' % cpu_info)
NotImplementedError: Unsupported CPU.
processor	: 0
BogoMIPS	: 108.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x4
CPU part	: 0xd0b
CPU revision	: 1

processor	: 1
BogoMIPS	: 108.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x4
CPU part	: 0xd0b
CPU revision	: 1

processor	: 2
BogoMIPS	: 108.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x4
CPU part	: 0xd0b
CPU revision	: 1

processor	: 3
BogoMIPS	: 108.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x4
CPU part	: 0xd0b
CPU revision	: 1

Revision	: d04170
Serial		: 28a0b219c4dec773
Model		: Raspberry Pi 5 Model B Rev 1.0

**Comment by DevMiser** [comment]
Unfortunately, the installation does not work well with Raspberry Pi 5 and the new Bookworm OS.  For best results, please use a Raspberry Pi 4 and the legacy OS.

**Comment by tmart42** [comment]
Thank you for responding. I did end up setting it up on a legacy 4 after realizing it wouldn't work, and it works like a charm. Thank you!!
