### ISSUE TITLE
Issue with moving the files

### ISSUE THREAD

**Issue by ProfileNameIsOk** [DevMiser/DaVinci#3]
Step 6 in the read me file has been bugging me a bit. I've done all the correct prompts and created the correct accounts. However, when I type this final command I'm met with "mv: cannot move '/home/pi/DaVinci/Davinci_raspberry-pi.ppn' to '/home/pi/.local/lib/python3.9/site-packages/pvporcupine/resources/keyword_files/raspberry-pi': no such file or directory"

Any help will be greatly appreciated!

**Comment by DevMiser** [comment]
Here is the command that hopefully you can cut and paste:

mv /home/pi/DaVinci/DaVinci_raspberry-pi.ppn /home/pi/.local/lib/python3.9/site-packages/pvporcupine/resources/keyword_files/raspberry-pi

Note that there should be two blank spaces in your command - between "mv" and "/home" and between ".ppn" and "/home". Be sure to include them. There is no space in "site-packages".

**Comment by ProfileNameIsOk** [comment]
Thank you for the help! The command worked, I appreciate it greatly
