### ISSUE TITLE
ALSA lib error

### ISSUE THREAD

**Issue by RetoHB** [DevMiser/DaVinci#33]
On one of my DaVincis I am getting a lot of ALSA lib errors:

`ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occured`

The assistant seems to work more or less, but these errors do cause the voice to be full of static for half a second or so...

Any idea where this might come from?

**Comment by DownTheMyrWash** [comment]
ALSA is a sound library for Linux. It’s possible that your speaker/mic is configured incorrectly. Are you using a usb speaker, or an AV Jack?

**Comment by RetoHB** [comment]
USB, the one you suggest.
Underrun occured, can this have something to do with system performance?

**Comment by RetoHB** [comment]
Issue was related to a different process running on the same Pi.
